title: Jesús García
logo: ./img/logo.png
description: Página web personal de Jesús García, profesor de informática en el IES Mare Nostrum de Alicante.
github:
  is_project_page: false
  is_user_page: false
show_downloads: false
theme: jekyll-theme-minimal
